name: CreativeEssentials
version: '${project.version}'
main: com.logzinga.creativeessentials.CreativeEssentials
api-version: 1.19
commands:
  survival:
    description: Sets the Player to survival
    usage: /<command>

  creative:
    description: Sets the player to creative
    usage: /<command>

  spawn:
    description:  Teleports the Player to Spawn
    usage: /<command>
